Repository RealConrad/42miniRT, pull requests merged in 2024-01, with the labels that each got.

#20 Feat/object renderer
  .vscode/settings.json
  Makefile
  includes/mini_rt.h
  includes/renderer.h
  includes/structs.h
  src/input/input.c
  src/main.c
  src/parser/parser_utils.c
  src/render/amb_light.c
  src/render/intersection.c
  src/render/pixel_colour.c
  src/render/render_objects.c
  src/render/render_scene.c
  src/render/vector_operations.c
  src/utils/colour_utils.c
Labels: enhancement

#21 Bug/rendering
  Makefile
  includes/mini_rt.h
  includes/renderer.h
  includes/structs.h
  src/main.c
  src/render/intersection.c
  src/render/pixel_colour.c
  src/render/ray_calculations.c
  src/render/render_objects.c
  src/render/render_scene.c
  src/utils/ft_dabs.c
Labels: bug

#24 Feat/cleanup
  Makefile
  includes/mini_rt.h
  includes/renderer.h
  includes/vector.h
  src/render/anti_aliasing.c
  src/render/mlx.c
  src/render/pixel_colour.c
  src/render/ray_calculations.c
  src/render/render_scene.c
  src/utils/progress_bar.c
  src/utils/rand.c
  src/vec_utils.c/vector_operations.c
  src/vec_utils.c/vector_operations2.c
Labels: enhancement

#29 Now draw objects based on closest object
  includes/mini_rt.h
  src/render/intersection.c
  src/render/pixel_colour.c
Labels: enhancement

#36 Feat/cylinder
  includes/vector.h
  src/parser/parser.c
  src/render/intersection.c
  src/render/pixel_colour.c
  src/vec_utils.c/vector_operations.c
  src/vec_utils.c/vector_operations2.c
Labels: documentation
